# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 06:45
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'result',
                    models.IntegerField(choices=[(1, 'success'), (2, 'fail')])
                ),
                ('output', models.TextField(blank=True)),
                ('time', models.DateTimeField(auto_now=True)),
                (
                    'command',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='calls',
                        to='commands.Command'
                    )
                ),
            ],
        ),
    ]
