# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0002_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='source',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Api')], default=1),
            preserve_default=False,
        ),
    ]
