# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 11:41
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import backend.commands.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commands', '0003_call_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=backend.commands.models.generate_token, editable=False, max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
