# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 08:36
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0004_accesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='token',
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='calls',
                to='commands.AccessToken'
            ),
        ),
    ]
